apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator-admission-webhook
    app.kubernetes.io/version: 0.58.0-rhobs2
  name: prometheus-operator-admission-webhook
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: https
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-operator-admission-webhook
      app.kubernetes.io/version: 0.58.0-rhobs2
